version: '3.8'

services:
  # 1. React Frontend
  frontend:
    build: ./frontend
    ports:
      - "5173:5173" # Binds Vite's container port to your computer's port
    depends_on:
      - api-gateway

  # 2. API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - USER_SERVICE_URL=http://user-service:3001
      - POST_SERVICE_URL=http://post-service:3002
      - JOB_SERVICE_URL=http://job-service:3003

  # 3. User Service
  user-service:
    build: ./services/user-service
    environment:
      - PORT=3001

  # 4. Post Service
  post-service:
    build: ./services/post-service
    environment:
      - PORT=3002

  # 5. Job Service
  job-service:
    build: ./services/job-service
    environment:
      - PORT=3003